import { store } from '@/lib/db/memory-store';
import { Invoice, Customer } from '@/lib/types';
import { formatCurrency } from '@/lib/utils';

export interface AIChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  suggestedActions?: {
    label: string;
    actionType: 'SEND_REMINDER' | 'NUDGE_ALL_OVERDUE' | 'ESCALATE' | 'VIEW_INVOICE' | 'RUN_AUTOPILOT';
    payload?: any;
  }[];
}

export interface AutoGeneratedEmail {
  invoiceId: string;
  invoiceNumber: string;
  customerName: string;
  customerEmail: string;
  amountDue: number;
  daysOverdue: number;
  stage: string;
  subject: string;
  body: string;
  paymentLink: string;
  status: 'DISPATCHED' | 'QUEUED';
}

export class AIAssistantService {
  /**
   * Generates intelligent AI responses to natural language queries regarding AR and debtors.
   */
  public static processQuery(prompt: string): AIChatMessage {
    const lower = prompt.toLowerCase();
    const stats = store.getDashboardStats();
    const invoices = store.getInvoices();
    const overdueInvoices = invoices.filter((i) => i.status === 'OVERDUE' || i.status === 'ESCALATED');

    const timestamp = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const id = `msg_${Date.now()}`;

    // 1. Check for Highest Risk / Overdue Query
    if (lower.includes('who owes') || lower.includes('highest') || lower.includes('overdue') || lower.includes('risk')) {
      const topOverdue = [...overdueInvoices].sort((a, b) => b.amountDue - a.amountDue).slice(0, 3);
      
      const debtorList = topOverdue
        .map(
          (inv) =>
            `• **${inv.customer?.companyName || 'Debtor'}**: ${formatCurrency(inv.amountDue)} (${inv.daysOverdue} days overdue, Invoice #${inv.invoiceNumber})`
        )
        .join('\n');

      return {
        id,
        role: 'assistant',
        timestamp,
        content: `Here are the top outstanding accounts requiring attention:\n\n${debtorList}\n\n**Total Overdue Balance**: ${formatCurrency(stats.totalOverdue)} across ${stats.invoicesCount.overdue} delinquent invoices. Would you like me to dispatch calibrated reminder emails to all of them?`,
        suggestedActions: [
          { label: '⚡ Nudge All Overdue Debtors', actionType: 'NUDGE_ALL_OVERDUE' },
          { label: '🤖 Run Auto-Pilot Follow-Up', actionType: 'RUN_AUTOPILOT' },
        ],
      };
    }

    // 2. Draft / Generate email reminder query
    if (lower.includes('draft') || lower.includes('email') || lower.includes('write') || lower.includes('template')) {
      const sample = overdueInvoices[0] || invoices[0];
      const customerName = sample?.customer?.companyName || 'Client';
      const days = sample?.daysOverdue || 7;
      
      const draftedSubject = days > 14
        ? `URGENT: Outstanding Balance for Invoice ${sample.invoiceNumber} (${days} days overdue)`
        : `Reminder: Invoice ${sample.invoiceNumber} payment due (${formatCurrency(sample.amountDue)})`;

      const draftedBody = `Dear ${sample.customer?.name || 'Finance Team'},\n\nWe hope you are having a productive week.\n\nOur records indicate that invoice **${sample.invoiceNumber}** for **${formatCurrency(sample.amountDue)}** was due on ${new Date(sample.dueDate).toLocaleDateString()} and is currently **${days} days past due**.\n\nPlease complete settlement using your secure 1-click payment link:\n👉 ${sample.paymentLinkUrl}\n\nIf you have already processed this payment or need a copy of the original deliverables, please let us know immediately.\n\nBest regards,\nAccounts Receivable Team`;

      return {
        id,
        role: 'assistant',
        timestamp,
        content: `I've generated a tone-calibrated reminder for **${customerName}**:\n\n**Subject**: ${draftedSubject}\n\n\`\`\`text\n${draftedBody}\n\`\`\`\n\nWould you like me to send this email right now via our automated email engine?`,
        suggestedActions: [
          {
            label: `✉️ Send to ${sample.customer?.email || 'Customer'}`,
            actionType: 'SEND_REMINDER',
            payload: { invoiceId: sample.id, message: draftedBody },
          },
        ],
      };
    }

    // 3. Cashflow / Collection forecast query
    if (lower.includes('cash') || lower.includes('forecast') || lower.includes('collect') || lower.includes('stats')) {
      return {
        id,
        role: 'assistant',
        timestamp,
        content: `📊 **Cashflow & Collection Summary**:\n• **Collected This Month**: ${formatCurrency(stats.totalPaidThisMonth)} (+${stats.paidTrendPercent}% increase)\n• **Total Outstanding**: ${formatCurrency(stats.totalOutstanding)}\n• **Projected Inflow (Next 30d)**: $118,000\n• **Collection Efficiency Index (CEI)**: ${stats.collectionEfficiencyIndex}%\n• **Current DSO**: ${stats.averageDaysToPay} Days (14 days faster than industry average)\n\nAutonomous cadence sequences have accelerated your settlement speed by **2.4x**.`,
        suggestedActions: [
          { label: '📈 View Detailed Cashflow', actionType: 'VIEW_INVOICE' },
          { label: '🤖 Trigger Auto-Pilot Reminders', actionType: 'RUN_AUTOPILOT' },
        ],
      };
    }

    // 4. Default Assistant Response
    return {
      id,
      role: 'assistant',
      timestamp,
      content: `I am your **CollectFlow Autonomous AR Copilot**. I continuously monitor unpaid invoices, calculate debtor default risks, and automatically dispatch tone-calibrated reminder emails.\n\nYou can ask me:\n• *"Who owes us the most money right now?"*\n• *"Draft a polite follow-up email for Apex Logistics"*\n• *"What is our projected cashflow for this month?"*\n• *"Send automated reminder emails to all overdue clients"*\n\nHow can I help you accelerate cash collection today?`,
      suggestedActions: [
        { label: '🚨 Check Overdue Debtors', actionType: 'NUDGE_ALL_OVERDUE' },
        { label: '🤖 Run Autonomous Email Cadence', actionType: 'RUN_AUTOPILOT' },
      ],
    };
  }

  /**
   * Autonomous Auto-Pilot Engine: Scans all invoices and dispatches personalized reminders with 1-click payment links.
   */
  public static runAutoPilotEngine(): {
    processedCount: number;
    dispatchedEmails: AutoGeneratedEmail[];
    totalRecoverableAmount: number;
    summary: string;
  } {
    const invoices = store.getInvoices();
    const dispatchedEmails: AutoGeneratedEmail[] = [];
    let totalRecoverableAmount = 0;

    const now = new Date();

    for (const invoice of invoices) {
      if (invoice.status === 'PAID' || invoice.status === 'DRAFT' || invoice.status === 'IN_DISPUTE') {
        continue;
      }

      const daysOverdue = invoice.daysOverdue || 0;
      const customer = invoice.customer || store.getCustomerById(invoice.customerId);
      const customerEmail = customer?.email || 'finance@client.com';
      const customerName = customer?.companyName || 'Client Company';
      const contactPerson = customer?.name || 'Finance Lead';

      let stage = 'Friendly Due Date Reminder';
      let subject = `Reminder: Invoice ${invoice.invoiceNumber} is due (${formatCurrency(invoice.amountDue)})`;
      let toneOpening = `This is a friendly reminder that invoice #${invoice.invoiceNumber} ($${invoice.amountDue.toLocaleString()}) is due.`;

      if (daysOverdue > 21) {
        stage = 'Delinquency & Escalation Notice';
        subject = `URGENT: Delinquent Balance Notice - ${invoice.invoiceNumber} (${daysOverdue} days past due)`;
        toneOpening = `This is an urgent notice regarding overdue invoice #${invoice.invoiceNumber} ($${invoice.amountDue.toLocaleString()}), which is now ${daysOverdue} days past due. Immediate settlement is required to prevent account suspension.`;
      } else if (daysOverdue > 10) {
        stage = '14-Day Late Assessment Warning';
        subject = `Overdue Follow-Up: Invoice ${invoice.invoiceNumber} - Late Assessment Pending`;
        toneOpening = `Our records indicate that invoice #${invoice.invoiceNumber} for $${invoice.amountDue.toLocaleString()} remains outstanding past the agreed Net-${customer?.paymentTermsDays || 30} terms.`;
      } else if (daysOverdue > 0) {
        stage = '7-Day Follow-Up';
        subject = `Follow-Up: Payment for Invoice ${invoice.invoiceNumber}`;
        toneOpening = `We noticed that invoice #${invoice.invoiceNumber} ($${invoice.amountDue.toLocaleString()}) was due on ${new Date(invoice.dueDate).toLocaleDateString()} and is currently ${daysOverdue} days overdue.`;
      }

      const body = `Dear ${contactPerson},\n\n${toneOpening}\n\nPlease click the secure 1-click link below to settle this balance via credit card or ACH transfer:\n\n👉 Pay Now: ${invoice.paymentLinkUrl}\n\nSummary:\n• Invoice: ${invoice.invoiceNumber}\n• Amount Due: ${formatCurrency(invoice.amountDue)}\n• Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}\n\nThank you for your prompt attention.\n\nWarm regards,\nAccounts Receivable Team`;

      // Log communication into memory store
      invoice.communications = invoice.communications || [];
      invoice.communications.unshift({
        id: `comm_auto_${Date.now()}_${Math.random().toString(36).substr(2, 5)}`,
        invoiceId: invoice.id,
        customerId: invoice.customerId,
        type: daysOverdue > 20 ? 'ESCALATION_LETTER' : 'EMAIL',
        subject,
        body,
        channel: 'email',
        status: 'DELIVERED',
        sentAt: new Date().toISOString(),
      });

      invoice.remindersSentCount += 1;
      invoice.lastReminderAt = new Date().toISOString();
      totalRecoverableAmount += invoice.amountDue;

      dispatchedEmails.push({
        invoiceId: invoice.id,
        invoiceNumber: invoice.invoiceNumber,
        customerName,
        customerEmail,
        amountDue: invoice.amountDue,
        daysOverdue,
        stage,
        subject,
        body,
        paymentLink: invoice.paymentLinkUrl,
        status: 'DISPATCHED',
      });
    }

    return {
      processedCount: dispatchedEmails.length,
      dispatchedEmails,
      totalRecoverableAmount,
      summary: `Autonomous AR Engine scanned ${invoices.length} invoices and automatically dispatched ${dispatchedEmails.length} personalized reminder emails targeting ${formatCurrency(totalRecoverableAmount)} in outstanding receivables.`,
    };
  }
}
