import { Customer, Invoice, Workflow, Integration, User } from '../types';

export const SEED_USERS: User[] = [
  {
    id: 'usr_01',
    email: 'sarah.jenkins@apexmedia.io',
    name: 'Sarah Jenkins',
    role: 'OWNER',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org_apex',
  },
  {
    id: 'usr_02',
    email: 'marcus.vance@apexmedia.io',
    name: 'Marcus Vance',
    role: 'FINANCE_MANAGER',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org_apex',
  },
  {
    id: 'usr_03',
    email: 'elena.gomez@apexmedia.io',
    name: 'Elena Gomez',
    role: 'COLLECTIONS_SPECIALIST',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    organizationId: 'org_apex',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    organizationId: 'org_apex',
    name: 'Alex Rivera',
    companyName: 'Nova Labs BioTech',
    email: 'accounts@novalabs.bio',
    phone: '+1 (415) 890-2134',
    address: '500 Howard St, San Francisco, CA',
    website: 'https://novalabs.bio',
    apContactName: 'Maria Chen (Head of AP)',
    apEmail: 'ap@novalabs.bio',
    sourceProvider: 'STRIPE',
    creditLimit: 50000,
    paymentTermsDays: 30,
    riskScore: 12,
    riskLevel: 'LOW',
    totalOutstanding: 0,
    totalPaid: 48500,
  },
  {
    id: 'cust_02',
    organizationId: 'org_apex',
    name: 'Jordan Chase',
    companyName: 'Horizon Media Group',
    email: 'finance@horizonmedia.co',
    phone: '+1 (212) 555-0199',
    address: '120 Broadway, New York, NY',
    website: 'https://horizonmedia.co',
    apContactName: 'Thomas Wright (VP Finance)',
    apEmail: 'twright@horizonmedia.co',
    sourceProvider: 'QUICKBOOKS',
    creditLimit: 50000,
    paymentTermsDays: 30,
    riskScore: 45,
    riskLevel: 'MEDIUM',
    totalOutstanding: 14200,
    totalPaid: 82000,
  },
  {
    id: 'cust_03',
    organizationId: 'org_apex',
    name: 'Derrick Vance',
    companyName: 'Apex Logistics LLC',
    email: 'billing@apexlogistics.us',
    phone: '+1 (312) 777-9021',
    address: '400 N Michigan Ave, Chicago, IL',
    website: 'https://apexlogistics.us',
    apContactName: 'Samuel Jackson (AP Lead)',
    apEmail: 'ap-team@apexlogistics.us',
    sourceProvider: 'QUICKBOOKS',
    creditLimit: 30000,
    paymentTermsDays: 15,
    riskScore: 78,
    riskLevel: 'HIGH',
    totalOutstanding: 18500,
    totalPaid: 29000,
  },
  {
    id: 'cust_04',
    organizationId: 'org_apex',
    name: 'Rachel Sterling',
    companyName: 'CloudScale SaaS Inc',
    email: 'rachel@cloudscale.io',
    phone: '+1 (650) 443-8821',
    address: '220 University Ave, Palo Alto, CA',
    website: 'https://cloudscale.io',
    apContactName: 'Kevin Patel (Controller)',
    apEmail: 'kpatel@cloudscale.io',
    sourceProvider: 'STRIPE',
    creditLimit: 60000,
    paymentTermsDays: 30,
    riskScore: 8,
    riskLevel: 'LOW',
    totalOutstanding: 8900,
    totalPaid: 115000,
  },
  {
    id: 'cust_05',
    organizationId: 'org_apex',
    name: 'Vikram Patel',
    companyName: 'Summit Retail Partners',
    email: 'vpatel@summitretail.com',
    phone: '+1 (512) 889-1029',
    address: '701 Brazos St, Austin, TX',
    website: 'https://summitretail.com',
    apContactName: 'Lisa Gomez (Finance Clerk)',
    apEmail: 'billing@summitretail.com',
    sourceProvider: 'XERO',
    creditLimit: 20000,
    paymentTermsDays: 30,
    riskScore: 92,
    riskLevel: 'CRITICAL',
    totalOutstanding: 9400,
    totalPaid: 14000,
  },
  {
    id: 'cust_06',
    organizationId: 'org_apex',
    name: 'Claire Beauchamp',
    companyName: 'Vantage Point Advisory',
    email: 'claire@vpadvisory.com',
    phone: '+1 (617) 320-4491',
    address: '100 Federal St, Boston, MA',
    website: 'https://vpadvisory.com',
    apContactName: 'Arthur Hastings (Partner)',
    apEmail: 'ahastings@vpadvisory.com',
    sourceProvider: 'STRIPE',
    creditLimit: 40000,
    paymentTermsDays: 30,
    riskScore: 18,
    riskLevel: 'LOW',
    totalOutstanding: 0,
    totalPaid: 64000,
  },
  {
    id: 'cust_07',
    organizationId: 'org_apex',
    name: 'Dr. Evelyn Thorne',
    companyName: 'Nexis BioHealth Inc',
    email: 'ethorne@nexisbio.org',
    phone: '+1 (858) 555-8392',
    address: '10300 Campus Point Dr, San Diego, CA',
    website: 'https://nexisbio.org',
    apContactName: 'Brenda Miller (Grants & AP)',
    apEmail: 'grants-ap@nexisbio.org',
    sourceProvider: 'QUICKBOOKS',
    creditLimit: 45000,
    paymentTermsDays: 30,
    riskScore: 64,
    riskLevel: 'HIGH',
    totalOutstanding: 22000,
    totalPaid: 35000,
  },
  {
    id: 'cust_08',
    organizationId: 'org_apex',
    name: 'Liam Zhang',
    companyName: 'Krypton Cloud Solutions',
    email: 'lzhang@kryptoncloud.io',
    phone: '+1 (206) 912-4019',
    address: '1201 3rd Ave, Seattle, WA',
    website: 'https://kryptoncloud.io',
    apContactName: 'Nina Rostova (Accounting)',
    apEmail: 'nrostova@kryptoncloud.io',
    sourceProvider: 'STRIPE',
    creditLimit: 35000,
    paymentTermsDays: 30,
    riskScore: 28,
    riskLevel: 'LOW',
    totalOutstanding: 9000,
    totalPaid: 51000,
  },
  {
    id: 'cust_09',
    organizationId: 'org_apex',
    name: 'Harrison Ford-Smith',
    companyName: 'Vanguard Financial Advisory',
    email: 'harrison@vanguardfinancial.net',
    phone: '+1 (704) 332-9011',
    address: '200 S Tryon St, Charlotte, NC',
    website: 'https://vanguardfinancial.net',
    apContactName: 'Eleanor Vance (Treasurer)',
    apEmail: 'treasury@vanguardfinancial.net',
    sourceProvider: 'QUICKBOOKS',
    creditLimit: 50000,
    paymentTermsDays: 30,
    riskScore: 55,
    riskLevel: 'MEDIUM',
    totalOutstanding: 15000,
    totalPaid: 45000,
  },
  {
    id: 'cust_10',
    organizationId: 'org_apex',
    name: 'Chloe Monet',
    companyName: 'Starlight Creative Labs',
    email: 'chloe@starlightcreative.co',
    phone: '+1 (310) 490-1122',
    address: '9200 Sunset Blvd, Los Angeles, CA',
    website: 'https://starlightcreative.co',
    apContactName: 'Lucas Grey (Finance Ops)',
    apEmail: 'lucas@starlightcreative.co',
    sourceProvider: 'FRESHBOOKS',
    creditLimit: 25000,
    paymentTermsDays: 30,
    riskScore: 15,
    riskLevel: 'LOW',
    totalOutstanding: 6500,
    totalPaid: 38000,
  },
  {
    id: 'cust_11',
    organizationId: 'org_apex',
    name: 'Gregory Paulson',
    companyName: 'Beacon Health Systems',
    email: 'gpaulson@beaconhealth.com',
    phone: '+1 (615) 890-4411',
    address: '3300 West End Ave, Nashville, TN',
    website: 'https://beaconhealth.com',
    apContactName: 'Donna Henderson (Procurement Director)',
    apEmail: 'dhenderson@beaconhealth.com',
    sourceProvider: 'QUICKBOOKS',
    creditLimit: 100000,
    paymentTermsDays: 45,
    riskScore: 20,
    riskLevel: 'LOW',
    totalOutstanding: 45000,
    totalPaid: 180000,
  },
  {
    id: 'cust_12',
    organizationId: 'org_apex',
    name: 'Bradley Cooper-Hayes',
    companyName: 'Pinnacle Real Estate Group',
    email: 'bcooper@pinnaclerealty.us',
    phone: '+1 (305) 778-9900',
    address: '1111 Brickell Ave, Miami, FL',
    website: 'https://pinnaclerealty.us',
    apContactName: 'Victoria Sterling (CFO)',
    apEmail: 'vsterling@pinnaclerealty.us',
    sourceProvider: 'XERO',
    creditLimit: 30000,
    paymentTermsDays: 15,
    riskScore: 82,
    riskLevel: 'HIGH',
    totalOutstanding: 11750,
    totalPaid: 22000,
  },
  {
    id: 'cust_13',
    organizationId: 'org_apex',
    name: 'Maya Lin',
    companyName: 'BlueWave E-Commerce',
    email: 'maya@bluewavestore.com',
    phone: '+1 (503) 221-8844',
    address: '1120 NW Couch St, Portland, OR',
    website: 'https://bluewavestore.com',
    apContactName: 'Chris Evans (AP Lead)',
    apEmail: 'payments@bluewavestore.com',
    sourceProvider: 'STRIPE',
    creditLimit: 20000,
    paymentTermsDays: 30,
    riskScore: 35,
    riskLevel: 'MEDIUM',
    totalOutstanding: 7800,
    totalPaid: 42000,
  },
  {
    id: 'cust_14',
    organizationId: 'org_apex',
    name: 'Siddharth Rao',
    companyName: 'Quantum AI Research',
    email: 'srao@quantumresearch.ai',
    phone: '+1 (408) 662-3300',
    address: '3000 Sand Hill Rd, Menlo Park, CA',
    website: 'https://quantumresearch.ai',
    apContactName: 'Ananya Sharma (Operations)',
    apEmail: 'finance@quantumresearch.ai',
    sourceProvider: 'STRIPE',
    creditLimit: 40000,
    paymentTermsDays: 30,
    riskScore: 10,
    riskLevel: 'LOW',
    totalOutstanding: 0,
    totalPaid: 60000,
  },
  {
    id: 'cust_15',
    organizationId: 'org_apex',
    name: 'Nathaniel Drake',
    companyName: 'AeroDynamics Corp',
    email: 'ndrake@aerodynamics.io',
    phone: '+1 (303) 554-2211',
    address: '1700 Lincoln St, Denver, CO',
    website: 'https://aerodynamics.io',
    apContactName: 'Elena Fisher (Controller)',
    apEmail: 'efisher@aerodynamics.io',
    sourceProvider: 'QUICKBOOKS',
    creditLimit: 60000,
    paymentTermsDays: 30,
    riskScore: 14,
    riskLevel: 'LOW',
    totalOutstanding: 0,
    totalPaid: 76800,
  },
];

// 15 Realistic, Varied Sample Invoices with Edge Cases
export const SEED_INVOICES: Invoice[] = [
  // 1. ESCALATED (38 days overdue, legal letter dispatched)
  {
    id: 'inv_01',
    organizationId: 'org_apex',
    customerId: 'cust_03',
    customer: SEED_CUSTOMERS[2],
    invoiceNumber: 'INV-2024-0089',
    amount: 18500,
    amountPaid: 0,
    amountDue: 18500,
    currency: 'USD',
    issueDate: '2024-07-15T00:00:00Z',
    dueDate: '2024-07-25T00:00:00Z',
    status: 'ESCALATED',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_01',
    notes: 'Q3 Enterprise Demand Gen Campaign Retainer - Final Notice.',
    remindersSentCount: 4,
    lastReminderAt: '2024-08-28T14:20:00Z',
    daysOverdue: 38,
    createdAt: '2024-07-15T09:00:00Z',
    items: [
      { id: 'item_101', invoiceId: 'inv_01', description: 'Enterprise Demand Gen Retainer', quantity: 1, unitPrice: 15000, amount: 15000 },
      { id: 'item_102', invoiceId: 'inv_01', description: 'HubSpot Automation Integration', quantity: 1, unitPrice: 3500, amount: 3500 },
    ],
    communications: [
      {
        id: 'comm_101',
        invoiceId: 'inv_01',
        customerId: 'cust_03',
        type: 'EMAIL',
        subject: 'Reminder: Invoice INV-2024-0089 is due in 3 days',
        body: 'Hi Derrick, this is a courtesy note that invoice INV-2024-0089 ($18,500) will be due on July 25.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-07-22T09:00:00Z',
        openedAt: '2024-07-22T11:42:00Z',
      },
      {
        id: 'comm_102',
        invoiceId: 'inv_01',
        customerId: 'cust_03',
        type: 'EMAIL',
        subject: 'Due Today: Invoice INV-2024-0089 ($18,500.00)',
        body: 'Hi Derrick, Invoice INV-2024-0089 is due today. Click to pay securely via credit card or ACH.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-07-25T09:00:00Z',
        openedAt: '2024-07-25T10:15:00Z',
        clickedAt: '2024-07-25T10:16:00Z',
      },
      {
        id: 'comm_103',
        invoiceId: 'inv_01',
        customerId: 'cust_03',
        type: 'EMAIL',
        subject: 'Overdue: INV-2024-0089 (7 days past due)',
        body: 'Hi Derrick, We have not received payment for invoice INV-2024-0089. Please resolve to avoid service interruption.',
        channel: 'email',
        status: 'DELIVERED',
        sentAt: '2024-08-01T09:00:00Z',
      },
      {
        id: 'comm_104',
        invoiceId: 'inv_01',
        customerId: 'cust_03',
        type: 'ESCALATION_LETTER',
        subject: 'URGENT: Executive Escalation - Outstanding Invoice INV-2024-0089',
        body: 'Dear Derrick Vance, Your account is currently 30+ days past due with an outstanding balance of $18,500.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-28T14:20:00Z',
        openedAt: '2024-08-28T16:05:00Z',
      },
    ],
  },

  // 2. OVERDUE (14 days overdue, link clicked)
  {
    id: 'inv_02',
    organizationId: 'org_apex',
    customerId: 'cust_02',
    customer: SEED_CUSTOMERS[1],
    invoiceNumber: 'INV-2024-0104',
    amount: 14200,
    amountPaid: 0,
    amountDue: 14200,
    currency: 'USD',
    issueDate: '2024-08-01T00:00:00Z',
    dueDate: '2024-08-18T00:00:00Z',
    status: 'OVERDUE',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_02',
    notes: 'Paid Media Creative Production & Ad Spend Allocation',
    remindersSentCount: 2,
    lastReminderAt: '2024-08-25T09:30:00Z',
    daysOverdue: 14,
    createdAt: '2024-08-01T08:30:00Z',
    items: [
      { id: 'item_201', invoiceId: 'inv_02', description: 'Creative Video Asset Suite', quantity: 4, unitPrice: 2800, amount: 11200 },
      { id: 'item_202', invoiceId: 'inv_02', description: 'Landing Page Conversion Optimization', quantity: 1, unitPrice: 3000, amount: 3000 },
    ],
    communications: [
      {
        id: 'comm_201',
        invoiceId: 'inv_02',
        customerId: 'cust_02',
        type: 'EMAIL',
        subject: 'Invoice INV-2024-0104 Due Today',
        body: 'Hi Jordan, invoice INV-2024-0104 is due today.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-18T09:00:00Z',
        openedAt: '2024-08-18T11:00:00Z',
      },
      {
        id: 'comm_202',
        invoiceId: 'inv_02',
        customerId: 'cust_02',
        type: 'EMAIL',
        subject: 'Payment Reminder: INV-2024-0104 is 7 days overdue',
        body: 'Hi Jordan, quick friendly nudge on invoice INV-2024-0104 ($14,200.00).',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-25T09:30:00Z',
        openedAt: '2024-08-25T10:14:00Z',
        clickedAt: '2024-08-25T10:15:00Z',
      },
    ],
  },

  // 3. OVERDUE (7 days overdue, Critical Risk Debtor)
  {
    id: 'inv_03',
    organizationId: 'org_apex',
    customerId: 'cust_05',
    customer: SEED_CUSTOMERS[4],
    invoiceNumber: 'INV-2024-0112',
    amount: 9400,
    amountPaid: 0,
    amountDue: 9400,
    currency: 'USD',
    issueDate: '2024-08-10T00:00:00Z',
    dueDate: '2024-08-25T00:00:00Z',
    status: 'OVERDUE',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_03',
    notes: 'Shopify Plus Custom App Architecture & Store Launch',
    remindersSentCount: 1,
    lastReminderAt: '2024-08-26T08:00:00Z',
    daysOverdue: 7,
    createdAt: '2024-08-10T10:00:00Z',
    items: [
      { id: 'item_301', invoiceId: 'inv_03', description: 'Shopify Plus Backend Architecture', quantity: 1, unitPrice: 9400, amount: 9400 },
    ],
    communications: [
      {
        id: 'comm_301',
        invoiceId: 'inv_03',
        customerId: 'cust_05',
        type: 'EMAIL',
        subject: 'Friendly Reminder: Invoice INV-2024-0112 ($9,400)',
        body: 'Hi Vikram, please review invoice INV-2024-0112 which was due on Aug 25.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-26T08:00:00Z',
        openedAt: '2024-08-26T14:30:00Z',
      },
    ],
  },

  // 4. IN_DISPUTE (Customer disputed milestone deliverable)
  {
    id: 'inv_04',
    organizationId: 'org_apex',
    customerId: 'cust_07',
    customer: SEED_CUSTOMERS[6],
    invoiceNumber: 'INV-2024-0115',
    amount: 22000,
    amountPaid: 0,
    amountDue: 22000,
    currency: 'USD',
    issueDate: '2024-08-05T00:00:00Z',
    dueDate: '2024-08-20T00:00:00Z',
    status: 'IN_DISPUTE',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_04',
    notes: 'Phase 2 Clinical Data Pipeline Integration',
    disputeReason: 'Client requested audit of developer sprint hours for milestone 2 before releasing payment. Automated cadence paused.',
    remindersSentCount: 1,
    lastReminderAt: '2024-08-21T09:00:00Z',
    daysOverdue: 12,
    createdAt: '2024-08-05T14:00:00Z',
    items: [
      { id: 'item_401', invoiceId: 'inv_04', description: 'Clinical Data Pipeline & HIPAA ETL', quantity: 1, unitPrice: 22000, amount: 22000 },
    ],
    communications: [
      {
        id: 'comm_401',
        invoiceId: 'inv_04',
        customerId: 'cust_07',
        type: 'EMAIL',
        subject: 'Invoice Dispute Notice Logged - INV-2024-0115',
        body: 'Hi Dr. Thorne, we have paused automated collections while our project director reviews milestone 2 deliverable sign-offs.',
        channel: 'email',
        status: 'DELIVERED',
        sentAt: '2024-08-22T11:00:00Z',
      },
    ],
  },

  // 5. PARTIALLY_PAID ($15k total, $6k paid, $9k remaining due soon)
  {
    id: 'inv_05',
    organizationId: 'org_apex',
    customerId: 'cust_08',
    customer: SEED_CUSTOMERS[7],
    invoiceNumber: 'INV-2024-0118',
    amount: 15000,
    amountPaid: 6000,
    amountDue: 9000,
    currency: 'USD',
    issueDate: '2024-08-12T00:00:00Z',
    dueDate: '2024-09-08T00:00:00Z',
    status: 'PARTIALLY_PAID',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_05',
    notes: 'Kubernetes Cloud Cost Optimization Sprint - Installment 1 of 2 settled.',
    remindersSentCount: 1,
    lastReminderAt: '2024-08-20T10:00:00Z',
    daysOverdue: 0,
    createdAt: '2024-08-12T11:20:00Z',
    items: [
      { id: 'item_501', invoiceId: 'inv_05', description: 'Cloud Architecture & FinOps Optimization', quantity: 1, unitPrice: 15000, amount: 15000 },
    ],
    communications: [
      {
        id: 'comm_501',
        invoiceId: 'inv_05',
        customerId: 'cust_08',
        type: 'EMAIL',
        subject: 'Partial Payment Confirmed: $6,000 for INV-2024-0118',
        body: 'Hi Liam, thank you! $6,000 has been credited. Remaining balance of $9,000 is due on Sept 08.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-20T10:00:00Z',
        openedAt: '2024-08-20T10:30:00Z',
      },
    ],
  },

  // 6. PARTIALLY_PAID + OVERDUE ($30k total, $15k paid, $15k balance 10 days overdue)
  {
    id: 'inv_06',
    organizationId: 'org_apex',
    customerId: 'cust_09',
    customer: SEED_CUSTOMERS[8],
    invoiceNumber: 'INV-2024-0120',
    amount: 30000,
    amountPaid: 15000,
    amountDue: 15000,
    currency: 'USD',
    issueDate: '2024-07-22T00:00:00Z',
    dueDate: '2024-08-22T00:00:00Z',
    status: 'PARTIALLY_PAID',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_06',
    notes: 'Wealth Advisory Portal UI/UX Redesign - Deposit received, final balance past due.',
    remindersSentCount: 2,
    lastReminderAt: '2024-08-29T09:00:00Z',
    daysOverdue: 10,
    createdAt: '2024-07-22T13:00:00Z',
    items: [
      { id: 'item_601', invoiceId: 'inv_06', description: 'Design System & Client Portal Frontend', quantity: 1, unitPrice: 30000, amount: 30000 },
    ],
    communications: [
      {
        id: 'comm_601',
        invoiceId: 'inv_06',
        customerId: 'cust_09',
        type: 'EMAIL',
        subject: 'Overdue Notice: $15,000 remaining on INV-2024-0120',
        body: 'Hi Harrison, gentle follow up on the final milestone balance for the portal project.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-29T09:00:00Z',
        openedAt: '2024-08-29T10:15:00Z',
      },
    ],
  },

  // 7. VIEWED (Due in 4 days, client opened portal twice)
  {
    id: 'inv_07',
    organizationId: 'org_apex',
    customerId: 'cust_04',
    customer: SEED_CUSTOMERS[3],
    invoiceNumber: 'INV-2024-0122',
    amount: 8900,
    amountPaid: 0,
    amountDue: 8900,
    currency: 'USD',
    issueDate: '2024-08-15T00:00:00Z',
    dueDate: '2024-09-05T00:00:00Z',
    status: 'VIEWED',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_07',
    notes: 'Monthly Growth Marketing & B2B ABM Strategy Retainer',
    remindersSentCount: 1,
    lastReminderAt: '2024-08-16T10:00:00Z',
    daysOverdue: 0,
    createdAt: '2024-08-15T10:00:00Z',
    items: [
      { id: 'item_701', invoiceId: 'inv_07', description: 'Monthly ABM Engine Execution', quantity: 1, unitPrice: 8900, amount: 8900 },
    ],
    communications: [
      {
        id: 'comm_701',
        invoiceId: 'inv_07',
        customerId: 'cust_04',
        type: 'EMAIL',
        subject: 'New Invoice from Apex Growth: INV-2024-0122',
        body: 'Hi Rachel, your new invoice INV-2024-0122 ($8,900.00) is ready for review.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-16T10:00:00Z',
        openedAt: '2024-08-16T10:45:00Z',
      },
    ],
  },

  // 8. SENT (Due in 12 days, Net-30 monthly retainer)
  {
    id: 'inv_08',
    organizationId: 'org_apex',
    customerId: 'cust_10',
    customer: SEED_CUSTOMERS[9],
    invoiceNumber: 'INV-2024-0125',
    amount: 6500,
    amountPaid: 0,
    amountDue: 6500,
    currency: 'USD',
    issueDate: '2024-08-20T00:00:00Z',
    dueDate: '2024-09-13T00:00:00Z',
    status: 'SENT',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_08',
    notes: 'Brand Content Creation & Social Video Strategy Sprint',
    remindersSentCount: 0,
    daysOverdue: 0,
    createdAt: '2024-08-20T15:00:00Z',
    items: [
      { id: 'item_801', invoiceId: 'inv_08', description: 'Monthly Video Production & Asset Suite', quantity: 1, unitPrice: 6500, amount: 6500 },
    ],
    communications: [],
  },

  // 9. SENT (Due in 20 days, large enterprise Net-45 invoice)
  {
    id: 'inv_09',
    organizationId: 'org_apex',
    customerId: 'cust_11',
    customer: SEED_CUSTOMERS[10],
    invoiceNumber: 'INV-2024-0127',
    amount: 45000,
    amountPaid: 0,
    amountDue: 45000,
    currency: 'USD',
    issueDate: '2024-08-01T00:00:00Z',
    dueDate: '2024-09-21T00:00:00Z',
    status: 'SENT',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_09',
    notes: 'Q3 Enterprise Electronic Health Records UX Architecture',
    remindersSentCount: 0,
    daysOverdue: 0,
    createdAt: '2024-08-01T09:00:00Z',
    items: [
      { id: 'item_901', invoiceId: 'inv_09', description: 'Enterprise UX Research & Architecture', quantity: 1, unitPrice: 45000, amount: 45000 },
    ],
    communications: [],
  },

  // 10. PAID ($24,500 settled in full via Stripe ACH)
  {
    id: 'inv_10',
    organizationId: 'org_apex',
    customerId: 'cust_01',
    customer: SEED_CUSTOMERS[0],
    invoiceNumber: 'INV-2024-0098',
    amount: 24500,
    amountPaid: 24500,
    amountDue: 0,
    currency: 'USD',
    issueDate: '2024-07-20T00:00:00Z',
    dueDate: '2024-08-20T00:00:00Z',
    paidDate: '2024-08-18T16:30:00Z',
    status: 'PAID',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_10',
    notes: 'Biotech Brand Identity & Investor Deck Design sprint.',
    remindersSentCount: 1,
    lastReminderAt: '2024-08-17T09:00:00Z',
    daysOverdue: 0,
    createdAt: '2024-07-20T10:00:00Z',
    items: [
      { id: 'item_1001', invoiceId: 'inv_10', description: 'Brand Strategy & Visual Guidelines', quantity: 1, unitPrice: 16500, amount: 16500 },
      { id: 'item_1002', invoiceId: 'inv_10', description: 'Series B Pitch Deck Design', quantity: 1, unitPrice: 8000, amount: 8000 },
    ],
    communications: [
      {
        id: 'comm_1001',
        invoiceId: 'inv_10',
        customerId: 'cust_01',
        type: 'EMAIL',
        subject: 'Invoice INV-2024-0098 Paid in Full',
        body: 'Hi Alex, thank you! We have received your payment of $24,500.00 via Stripe ACH.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-18T16:35:00Z',
        openedAt: '2024-08-18T16:40:00Z',
      },
    ],
  },

  // 11. PAID ($32,000 settled via Wire Transfer)
  {
    id: 'inv_11',
    organizationId: 'org_apex',
    customerId: 'cust_06',
    customer: SEED_CUSTOMERS[5],
    invoiceNumber: 'INV-2024-0092',
    amount: 32000,
    amountPaid: 32000,
    amountDue: 0,
    currency: 'USD',
    issueDate: '2024-07-10T00:00:00Z',
    dueDate: '2024-08-10T00:00:00Z',
    paidDate: '2024-08-08T11:20:00Z',
    status: 'PAID',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_11',
    notes: 'Q3 Financial Model Web App UX & Design System',
    remindersSentCount: 0,
    daysOverdue: 0,
    createdAt: '2024-07-10T12:00:00Z',
    items: [
      { id: 'item_1101', invoiceId: 'inv_11', description: 'Full Platform UX System', quantity: 1, unitPrice: 32000, amount: 32000 },
    ],
    communications: [],
  },

  // 12. PAID ($16,800 paid on time)
  {
    id: 'inv_12',
    organizationId: 'org_apex',
    customerId: 'cust_15',
    customer: SEED_CUSTOMERS[14],
    invoiceNumber: 'INV-2024-0085',
    amount: 16800,
    amountPaid: 16800,
    amountDue: 0,
    currency: 'USD',
    issueDate: '2024-07-02T00:00:00Z',
    dueDate: '2024-08-02T00:00:00Z',
    paidDate: '2024-08-02T14:10:00Z',
    status: 'PAID',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_12',
    notes: 'Aerospace Systems Telemetry UI dashboard consulting',
    remindersSentCount: 1,
    lastReminderAt: '2024-07-30T09:00:00Z',
    daysOverdue: 0,
    createdAt: '2024-07-02T10:00:00Z',
    items: [
      { id: 'item_1201', invoiceId: 'inv_12', description: 'Telemetry Visualization Frontend', quantity: 1, unitPrice: 16800, amount: 16800 },
    ],
    communications: [],
  },

  // 13. DRAFT (Unsent project estimate)
  {
    id: 'inv_13',
    organizationId: 'org_apex',
    customerId: 'cust_14',
    customer: SEED_CUSTOMERS[13],
    invoiceNumber: 'INV-2024-0130',
    amount: 12000,
    amountPaid: 0,
    amountDue: 12000,
    currency: 'USD',
    issueDate: '2024-09-01T00:00:00Z',
    dueDate: '2024-10-01T00:00:00Z',
    status: 'DRAFT',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_13',
    notes: 'Q4 AI LLM Benchmark Analysis - Scope awaiting client PO signoff.',
    remindersSentCount: 0,
    daysOverdue: 0,
    createdAt: '2024-09-01T09:00:00Z',
    items: [
      { id: 'item_1301', invoiceId: 'inv_13', description: 'AI LLM Benchmark & Architecture Report', quantity: 1, unitPrice: 12000, amount: 12000 },
    ],
    communications: [],
  },

  // 14. OVERDUE (22 days overdue, High Risk Real Estate Group)
  {
    id: 'inv_14',
    organizationId: 'org_apex',
    customerId: 'cust_12',
    customer: SEED_CUSTOMERS[11],
    invoiceNumber: 'INV-2024-0132',
    amount: 11750,
    amountPaid: 0,
    amountDue: 11750,
    currency: 'USD',
    issueDate: '2024-07-20T00:00:00Z',
    dueDate: '2024-08-10T00:00:00Z',
    status: 'OVERDUE',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_14',
    notes: 'Luxury Property Showcase 3D Web Experience',
    remindersSentCount: 3,
    lastReminderAt: '2024-08-24T10:30:00Z',
    daysOverdue: 22,
    createdAt: '2024-07-20T11:00:00Z',
    items: [
      { id: 'item_1401', invoiceId: 'inv_14', description: '3D Interactive Virtual Tour WebGL Engine', quantity: 1, unitPrice: 11750, amount: 11750 },
    ],
    communications: [
      {
        id: 'comm_1401',
        invoiceId: 'inv_14',
        customerId: 'cust_12',
        type: 'EMAIL',
        subject: '14-Day Overdue Notice - INV-2024-0132 ($11,750)',
        body: 'Dear Bradley, Invoice INV-2024-0132 is 14 days overdue. Please remit payment via card or ACH.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-24T10:30:00Z',
        openedAt: '2024-08-24T15:10:00Z',
      },
    ],
  },

  // 15. SENT (Due tomorrow, polite reminder queued)
  {
    id: 'inv_15',
    organizationId: 'org_apex',
    customerId: 'cust_13',
    customer: SEED_CUSTOMERS[12],
    invoiceNumber: 'INV-2024-0135',
    amount: 7800,
    amountPaid: 0,
    amountDue: 7800,
    currency: 'USD',
    issueDate: '2024-08-02T00:00:00Z',
    dueDate: '2024-09-02T00:00:00Z',
    status: 'SENT',
    paymentLinkUrl: 'https://pay.collectflow.io/inv_15',
    notes: 'E-commerce Conversion Rate Optimization & Checkout Funnel Revamp',
    remindersSentCount: 1,
    lastReminderAt: '2024-08-30T09:00:00Z',
    daysOverdue: 0,
    createdAt: '2024-08-02T14:30:00Z',
    items: [
      { id: 'item_1501', invoiceId: 'inv_15', description: 'Shopify Checkout Optimization Sprint', quantity: 1, unitPrice: 7800, amount: 7800 },
    ],
    communications: [
      {
        id: 'comm_1501',
        invoiceId: 'inv_15',
        customerId: 'cust_13',
        type: 'EMAIL',
        subject: 'Courtesy Reminder: Invoice INV-2024-0135 due tomorrow',
        body: 'Hi Maya, quick courtesy note that invoice INV-2024-0135 ($7,800) is due for settlement tomorrow.',
        channel: 'email',
        status: 'OPENED',
        sentAt: '2024-08-30T09:00:00Z',
        openedAt: '2024-08-30T11:20:00Z',
      },
    ],
  },
];

export const SEED_WORKFLOW: Workflow = {
  id: 'wf_default',
  organizationId: 'org_apex',
  name: 'Standard Agency AR Recovery Cadence',
  description: 'Proactive 5-step automated follow-up sequence with progressive tone escalation.',
  isActive: true,
  isDefault: true,
  steps: [
    {
      id: 'step_1',
      workflowId: 'wf_default',
      stepOrder: 1,
      timing: 'BEFORE_DUE',
      offsetDays: -3,
      channel: 'EMAIL',
      templateSubject: 'Upcoming Invoice: {{invoice_number}} due in 3 days',
      templateBody: 'Hi {{customer_name}},\n\nThis is a quick courtesy note that invoice {{invoice_number}} for {{amount}} will be due on {{due_date}}.\n\nYou can review your invoice or pay in one click here: {{payment_link}}\n\nThanks for your partnership!\nBest regards,\n{{company_name}} Billing Team',
      isAutomated: true,
      requireApproval: false,
    },
    {
      id: 'step_2',
      workflowId: 'wf_default',
      stepOrder: 2,
      timing: 'ON_DUE',
      offsetDays: 0,
      channel: 'EMAIL',
      templateSubject: 'Due Today: Invoice {{invoice_number}} ({{amount}})',
      templateBody: 'Hi {{customer_name}},\n\nInvoice {{invoice_number}} is due for settlement today ({{due_date}}).\n\nPay immediately via ACH or Card: {{payment_link}}\n\nPlease reply if you have already scheduled this transfer.\n\nWarm regards,\n{{company_name}} Finance',
      isAutomated: true,
      requireApproval: false,
    },
    {
      id: 'step_3',
      workflowId: 'wf_default',
      stepOrder: 3,
      timing: 'AFTER_DUE',
      offsetDays: 7,
      channel: 'EMAIL',
      templateSubject: 'Overdue Notice: Invoice {{invoice_number}} (7 days past due)',
      templateBody: 'Hi {{customer_name}},\n\nWe noticed invoice {{invoice_number}} for {{amount}} is now 7 days past due.\n\nTo keep your services active without interruption, please complete payment today:\n{{payment_link}}\n\nIf you need an updated W-9 or payment details, just let us know.',
      isAutomated: true,
      requireApproval: false,
    },
    {
      id: 'step_4',
      workflowId: 'wf_default',
      stepOrder: 4,
      timing: 'AFTER_DUE',
      offsetDays: 14,
      channel: 'EMAIL',
      templateSubject: 'Urgent: Invoice {{invoice_number}} is 14 days overdue',
      templateBody: 'Attention {{customer_name}},\n\nOur records indicate that invoice {{invoice_number}} ({{amount}}) remains unpaid after 14 days.\n\nPlease remit payment immediately via the secure portal: {{payment_link}}\n\nUnpaid balances past 21 days may incur late interest fees according to our master agreement.',
      isAutomated: true,
      requireApproval: true,
    },
    {
      id: 'step_5',
      workflowId: 'wf_default',
      stepOrder: 5,
      timing: 'ESCALATION',
      offsetDays: 30,
      channel: 'ESCALATION',
      templateSubject: 'Final Notice & Account Suspension Warning - {{invoice_number}}',
      templateBody: 'Dear {{customer_name}},\n\nDespite multiple reminders, invoice {{invoice_number}} ({{amount}}) remains delinquent (30+ days overdue).\n\nPlease settle this account immediately: {{payment_link}}\n\nFailure to resolve by end of week will result in account suspension and referral to outside collections.',
      isAutomated: false,
      requireApproval: true,
    },
  ],
};

export const SEED_INTEGRATIONS: Integration[] = [
  {
    id: 'int_01',
    organizationId: 'org_apex',
    provider: 'STRIPE',
    status: 'CONNECTED',
    accountName: 'Apex Media Growth (acct_1NZ002x9a)',
    lastSyncAt: '2024-09-01T14:15:00Z',
    syncFrequency: 'Real-time Webhook & Hourly Sync',
    syncLog: 'Synced 15 invoices, 3 payments captured in last sync run.',
  },
  {
    id: 'int_02',
    organizationId: 'org_apex',
    provider: 'QUICKBOOKS',
    status: 'CONNECTED',
    accountName: 'Apex Agency Corp (Realm: 913034821)',
    lastSyncAt: '2024-09-01T12:00:00Z',
    syncFrequency: 'Every 6 Hours',
    syncLog: 'GL accounts matched. AR balance verified.',
  },
  {
    id: 'int_03',
    organizationId: 'org_apex',
    provider: 'XERO',
    status: 'DISCONNECTED',
    accountName: 'Not Connected',
    syncFrequency: 'Daily',
  },
  {
    id: 'int_04',
    organizationId: 'org_apex',
    provider: 'FRESHBOOKS',
    status: 'DISCONNECTED',
    accountName: 'Not Connected',
    syncFrequency: 'Daily',
  },
];
